### ISSUE TITLE
Graceful shutdown with existing websocket connections

### ISSUE THREAD

**Issue by tarrencev** [thodde/go-reverse-proxy#1]
Hi @thodde this is looking pretty good! I noticed you missed implementing the following though:

4. **Graceful Shutdown**:
    - Implement a graceful shutdown mechanism. When the proxy receives a shutdown signal (e.g., SIGINT or SIGTERM), it should:
        - Stop accepting new connections.
        - Wait for all ongoing HTTP requests to complete.
        - Maintain active WebSocket connections until they are closed by the client or backend server.
        - Provide a reasonable timeout period for ongoing WebSocket connections to close before forcefully shutting down.

**Comment by thodde** [comment]
@tarrencev Good callout! I wanted to get something sent over as soon as I could and I wasn't sure how much more time I could put into it. I was able to get it working this morning, so I will mark this issue as resolved :)
